language: objective-c
osx_image: xcode8.2
xcode_project: JSONRequest.xcodeproj
xcode_scheme: JSONRequest
xcode_sdk: iphonesimulator10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=JSONRequest.xcworkspace
  - IOS_FRAMEWORK_SCHEME="JSONRequest"
  - IOS_SDK=iphonesimulator10.2
  - FRAMEWORK_NAME=JSONRequest
  matrix:
  - DESTINATION="OS=9.3,name=iPhone 6S"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    POD_LINT="YES"
  - DESTINATION="OS=10.2,name=iPad Air 2"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    POD_LINT="NO"
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
install:
- "./install_swiftlint.sh"
- bundle install
script:
- set -o pipefail
- xcodebuild -version
- if [ $RUN_TESTS == "YES" ]; then travis_retry xcodebuild -workspace "$WORKSPACE"
  -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO
  test | xcpretty -c; else travis_retry xcodebuild -workspace "$WORKSPACE" -scheme
  "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO
  build | xcpretty -c; fi
- bundle exec danger
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME

deploy:
  provider: releases
  api_key:
    secure: i0jJqjj0OYk2mIHIpNEQ0gfosKqi/Qd9S1Hkga/CuOXpiZFuw8qEqEIIOxPiMsKZMoAFbr2aotNslDQf96wiFy1y7swX+FE+3UnRaczSxnyGceF8dsuVQttNIARD+5o0d0/PDogplsLle1NXahvUCGPg8kH9H0DTvv5gSVpK07o=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: hathway/JSONRequest
    tags: true
